### ISSUE TITLE
`ogma-core`: equivalence operator should be translated to `(==)`

### ISSUE THREAD

**Issue by Andersen0** [nasa/ogma#126] opened 2024-02-21 13:10 UTC
When using an equivalence operator (as used in, for example, FRETISH requirements as `<=>`) the returned Monitor will not be able to properly run because the Haskell Monitor cannot use the `<==>` operator that is defined in the code.

**The command used for generation of the Monitor was:**
_ogma fret-component-spec --fret-file-name fret_specifications.json > Monitor.hs_

**The command used for compiling and linking:**
_ghc -package copilot-c99 -package copilot-language -package copilot-libraries Monitor.hs_

**Acquired error message:**
```
Variable not in scope:
      (<==>) :: Stream Bool -> Stream Bool -> Stream Bool
    Suggested fix: Perhaps use ‘==>’ (imported from Copilot.Language)
```

**Suggested fix:**
Defining a custom infix operator that compares two boolean arguments and returns true if they are both true or both false
```
infix 4 <==>
(<==>) :: Stream (Bool) -> Stream (Bool) -> Stream (Bool)
a <==> b = a == b
```

**Comment by ivanperez-keera** [comment] 2024-03-01 18:56
Thank you @Andersen0 . I can confirm that the issue is there. This will be an easy fix.

**Comment by Andersen0** [comment] 2024-03-01 18:59
That is great news.

Sendt fra Outlook for iOS<https://aka.ms/o0ukef>
________________________________
Fra: Ivan Perez, PhD ***@***.***>
Sendt: Friday, March 1, 2024 7:56:42 PM
Til: nasa/ogma ***@***.***>
Kopi: Tage Andersen ***@***.***>; Mention ***@***.***>
Emne: Re: [nasa/ogma] Possible fix for missing equivalence operator (Issue #126)

You don't often get email from ***@***.*** Learn why this is important<https://aka.ms/LearnAboutSenderIdentification>

Thank you @Andersen0<https://github.com/Andersen0> . I can confirm that the issue is there. This will be an easy fix.

**Comment by ivanperez-keera** [comment] 2024-03-03 02:33
**Description**

The SMV to Copilot translator translates equivalences as `(<==>)`. However, that operator does not exist in Copilot, it is simply `(==)` for `Bool`s.

**Type**

- Bug: backend generates incorrect code.

**Additional context**

None.

**Requester**

- Tage Andersen and Elias Evjen Hartmark (NMBU, Norway)

**Method to check presence of bug**

Compiling a specification with `<->` in the `ptLTL` field produces Copilot code that does not compile:

```json
{
  "test_componentSpec": {
    "Functions": [
    ],
    "Internal_variables": [
    ],
    "Other_variables": [
      {
        "name": "a",
        "type": "bool"
      }
    ],
    "Requirements": [
      {
        "CoCoSpecCode": "true",
        "fretish": "unimportant",
        "name": "testCopilot-001",
        "ptLTL": "a <-> a"
      }
    ]
  }
}
```

**Expected result**

The execution above should produce a Copilot specification that can be compiled and where `==` is used in Copilot where an equivalence between booleans needs to be expressed.

**Desired result**

The execution above should produce a Copilot specification that can be compiled and where `==` is used in Copilot where an equivalence between booleans needs to be expressed.

**Proposed solution**

Modify the SMV translator to use `(==)` instead of `<==>`.

**Further notes**

None.

**Comment by ivanperez-keera** [comment] 2024-03-03 18:20
Change Manager: Confirmed that the issue exists.

**Comment by ivanperez-keera** [comment] 2024-03-03 18:21
Technical Lead: Confirmed that the issue should be addressed.

**Comment by ivanperez-keera** [comment] 2024-03-03 18:21
Technical Lead: Issue scheduled for fixing in Ogma 1.3.

Fix assigned to: @ivanperez-keera.

**Comment by ivanperez-keera** [comment] 2024-03-05 05:43
Implementor: Solution implemented, review requested.

**Comment by ivanperez-keera** [comment] 2024-03-05 05:52
Change Manager: Verified that:
- Solution is implemented:
  - [X] The code proposed compiles passes the tests. Details:
    Docker image:
    ```dockerfile
    FROM ubuntu:trusty
    
    RUN apt-get update
    
    RUN apt-get install --yes software-properties-common
    RUN add-apt-repository ppa:hvr/ghc
    RUN apt-get update
    
    RUN apt-get install --yes ghc-8.6.5 cabal-install-2.4
    RUN apt-get install --yes libz-dev
    
    ENV PATH=/opt/ghc/8.6.5/bin:/opt/cabal/2.4/bin:$PWD/.cabal-sandbox/bin:$PATH
    
    RUN cabal update
    RUN cabal v1-sandbox init
    RUN cabal v1-install alex happy
    RUN apt-get install --yes git
    
    # We install the application first and then test it, in case any tests need to
    # run the tool.
    CMD git clone $REPO && \
        cd $NAME && \
        git checkout $COMMIT && \
        cd .. && \
        cabal v1-install $NAME/$PAT**/ --enable-tests && \
        cabal v1-install $NAME/$PAT**/ --enable-tests --run-tests -j1
    ```
    Command:
    ```sh
    $ docker run -e "REPO=https://github.com/nasa/ogma" -e "NAME=ogma" -e PAT="ogma-" -e "COMMIT=d3ebffca2227cd61e1ea3e520fb5610f487e3633" -it ogma-test
    ```

  - [X] The solution proposed fixes the issues described. Details:
    The following Dockerfile uses the spec containing an equivalence operator in the SMV property, and it compiles the resulting Copilot code.
    ```Dockerfile
    --- Dockerfile-verify-126
    FROM ubuntu:trusty
    
    ENV DEBIAN_FRONTEND=noninteractive
    
    RUN apt-get update
    
    RUN apt-get install --yes software-properties-common
    RUN add-apt-repository ppa:hvr/ghc
    RUN apt-get update
    
    RUN apt-get install --yes ghc-8.6.5 cabal-install-2.4
    RUN apt-get install --yes libz-dev
    
    ENV PATH=/opt/ghc/8.6.5/bin:/opt/cabal/2.4/bin:$PWD/.cabal-sandbox/bin:$PATH
    
    RUN cabal update
    RUN cabal v1-sandbox init
    RUN cabal v1-install alex happy
    RUN cabal v1-install copilot-3.18.1
    RUN apt-get install --yes git
    
    ADD reqs.json /tmp/reqs.json
    
    CMD git clone $REPO && \
        cd $NAME && \
        git checkout $COMMIT && \
        cd .. && \
        cabal v1-install $NAME/$PAT**/ && \
        ogma fret-component-spec --fret-file-name /tmp/reqs.json > CS.hs && \
        cabal v1-exec -- ghc --make CS.hs && \
        echo "Success"

    --- reqs.json
    {
      "test_spec": {
        "Functions": [
        ],
        "Internal_variables": [
        ],
        "Other_variables": [
          {
            "name": "a",
            "type": "bool"
          }
        ],
        "Requirements": [
          {
            "CoCoSpecCode": "true",
            "fretish": "unimportant",
            "name": "testCopilot001",
            "ptLTL": "a <-> a"
          }
        ]
      }
    }
    ```
    Command:
    ```sh
    $ docker run -e "REPO=https://github.com/nasa/ogma" -e "NAME=ogma" -e PAT="ogma-" -e "COMMIT=d3ebffca2227cd61e1ea3e520fb5610f487e3633" -it ogma-verify-126
    ```
- [X] Implementation is documented. Details:
  No changes needed.
- [X] Change history is clear.
- [X] Commit messages are clear.
- [X] Changelogs are updated.
- [X] Examples are updated. Details:
  No examples affected.
- [X] Required version bumps are evaluated. Details:
  No bump needed (internal change).

**Comment by ivanperez-keera** [comment] 2024-03-05 05:52
Change Manager: Implementation ready to be merged.

**Closed** 2024-03-05 05:57 UTC
Labels: CR:Status:Verification, CR:Type:Bug
